### ISSUE TITLE
Proposition to add support of chassis/tyres/engines for each race

### ISSUE THREAD

**Issue by julesr0y** [f1db/f1db#40]
Hi,

Following the [discussion](https://github.com/f1db/f1db/discussions/37) I opened a few weeks ago about adding chassis data to f1db, I worked on it with the explanation that you gave about this, and I can now present what I made.
By searching my sources, I realised that it was possible to list all the chassis used from 1950 up to the current season, but also to determine which chassis was used by which entrant, by which driver, which tyre manufacturer, but also with which engine manufacturer and the model of engine for each race.

You will find below an explanation about my work, and a .zip file attached with the content.

### Zip attachment:

In the attached .zip file, you will find three folders:

- **chassis**:

  This folder contains a `chassisId.yml` file for each unique chassis used since 1950. For example, for the Ferrari 150° Italia (Scuderia Ferrari, 2011), there is a file named `ferrari-150-italia.yml`, which includes:

  ```yml
  id: ferrari-150-italia
  constructorId: ferrari
  name: 150° Italia
  fullName: Ferrari 150° Italia
  ```
- **engines**:

  This folder contains an `engineId.yml` file for each unique engine used since 1950. For example, for the BMW P82 V10 3.0 engine, there is a file named `bmw-p82-v10-3-0.yml`, which includes:

  ```yml
  id: bmw-p82-v10-3-0
  name: P82 V10 3.0
  engineManufacturerId: bmw
  layout: V10

  ```
- **entrants**:

  This folder mirrors the `f1db/src/data/seasons` folder and complements the data in each `entrants.yml` file already present in the subfolders.

  To illustrate the added data, let's revisit the case of Cooper Car Company during the 1953 season, which you previously mentioned [here](https://github.com/f1db/f1db/discussions/37#discussioncomment-10054042).

  With the current data, we have this:

  ```yml
  - entrantId: cooper-car-company
    countryId: united-kingdom
    constructors:
      - constructorId: cooper
        engineManufacturerId: bristol
        tyreManufacturerId: dunlop
        drivers:
          - driverId: adolfo-schwelm-cruz
            rounds: 1
          - driverId: alan-brown
            rounds: 1
          - driverId: john-barber
            rounds: 1
      - constructorId: cooper
        engineManufacturerId: alta
        tyreManufacturerId: dunlop
        driverId: stirling-moss
        rounds: 5,7,9
  ```

  This would now become the following with the attached files:

  ```yml
  - entrantId: cooper-car-company
    countryId: united-kingdom
    constructors:
      - constructorId: cooper
        engineManufacturerId: bristol
        tyreManufacturerId: dunlop
        engineId: bristol-bs1-l6-2-0
        drivers:
          - driverId: adolfo-schwelm-cruz
            rounds: 1
          - driverId: alan-brown
            rounds: 1
          - driverId: john-barber
            rounds: 1
        chassis:
          - chassisId: cooper-t20
            drivers:
              - driverId: adolfo-schwelm-cruz
                rounds: 1
              - driverId: alan-brown
                rounds: 1
          - chassisId: cooper-t23
            driverId: john-barber
            rounds: 1
      - constructorId: cooper
        engineManufacturerId: alta
        tyreManufacturerId: dunlop
        engineId: alta-f2-l4-2-0
        driverId: stirling-moss
        rounds: 5,7,9
        chassis:
          - chassisId: cooper-special
            driverId: stirling-moss
            rounds: 5
          - chassisId: cooper-t24
            driverId: stirling-moss
            rounds: 7,9
  ```

  With this data, we obtain more precise information. I've added an engineId element for the constructors, which includes the associated engine's ID, and a chassis element containing the chassis associated with the entrant, constructor, and engine. For example, we can now see that Stirling Moss indeed drove for Cooper Car Company in 1953 during rounds 5, 7, and 9 with a Cooper Special featuring Dunlop tyres and an Alta F2 L4 2.0 engine in round 5, and a Cooper T24 with the same engine model and tyres during rounds 7 and 9.

  ### Different cases:

  Each constructor for the same entrant is a unique combination of `constructorId`, `engineManufacturerId`, `tyreManufacturerId`, and `engineId`.
  This ensures that we have exactly the correct information for each round.

  #### Multiple tyre manufacturers:

  For example, in cases where an entrant used different tyre brands during the same season (Scuderia Ferrari, 1951):

  ```yml
  - entrantId: scuderia-ferrari
    countryId: italy
    constructors:
      - constructorId: ferrari
        engineManufacturerId: ferrari
        tyreManufacturerId: pirelli
        engineId: ferrari-375-v12-4-5
        drivers:
          - driverId: alberto-ascari
            rounds: 1,3,7-8
          - driverId: jose-froilan-gonzalez
            rounds: 7-8
          - driverId: luigi-villoresi
            rounds: 1,3,7-8
          - driverId: piero-taruffi
            rounds: 1,3,7-8
        chassis:
          - chassisId: ferrari-375
            drivers:
              - driverId: alberto-ascari
                rounds: 1,3,7-8
              - driverId: jose-froilan-gonzalez
                rounds: 7-8
              - driverId: luigi-villoresi
                rounds: 1,3,7-8
              - driverId: piero-taruffi
                rounds: 1,3,7-8
      - constructorId: ferrari
        engineManufacturerId: ferrari
        tyreManufacturerId: englebert
        engineId: ferrari-375-v12-4-5
        drivers:
          - driverId: alberto-ascari
            rounds: 4-6
          - driverId: jose-froilan-gonzalez
            rounds: 4-6
          - driverId: luigi-villoresi
            rounds: 4-6
          - driverId: piero-taruffi
            rounds: 6
        chassis:
          - chassisId: ferrari-375
            drivers:
              - driverId: alberto-ascari
                rounds: 4-6
              - driverId: jose-froilan-gonzalez
                rounds: 4-6
              - driverId: luigi-villoresi
                rounds: 4-6
              - driverId: piero-taruffi
                rounds: 6
  ```

  Since two tyre manufacturers were used (Pirelli and Englebert), there are two constructor elements, allowing us to determine the precise components (tyres/chassis/engine) used for each round and each driver in the entrant's season.

  #### Multiple engine manufacturers:

  In cases where the same entrant used multiple engine manufacturers during the same season, we get something similar to the previous example (Minardi Team, 1985):

  ```yml
  - entrantId: minardi-team
    countryId: italy
    constructors:
      - constructorId: minardi
        engineManufacturerId: ford
        tyreManufacturerId: pirelli
        engineId: ford-dfy-v8-3-0
        driverId: pierluigi-martini
        rounds: 1-2
        chassis:
          - chassisId: minardi-m185
            driverId: pierluigi-martini
            rounds: 1-2
      - constructorId: minardi
        engineManufacturerId: motori-moderni
        tyreManufacturerId: pirelli
        engineId: motori-moderni-615-90-v6-t-1-5
        driverId: pierluigi-martini
        rounds: 3-16
        chassis:
          - chassisId: minardi-m185
            driverId: pierluigi-martini
            rounds: 3-16
  ```

  Since two engine manufacturers were used (Ford and Motori Moderni), there are two constructor elements, allowing us to determine the precise combination of components (tyres/chassis/engine) used for each round and each driver in the entrant's season.

  #### Multiple engines:

  And for the cases where an entrant used different engines of the same engine manufacturer, we still have something similar (Benetton Tyrrell Team, 1983):

  ```yml
  - entrantId: benetton-tyrrell-team
    countryId: united-kingdom
    constructors:
      - constructorId: tyrrell
        engineManufacturerId: ford
        tyreManufacturerId: goodyear
        engineId: ford-dfv-v8-3-0
        drivers:
          - driverId: danny-sullivan
            rounds: 1-6
          - driverId: michele-alboreto
            rounds: 1-4
        chassis:
          - chassisId: tyrrell-011
            drivers:
              - driverId: danny-sullivan
                rounds: 1-6
              - driverId: michele-alboreto
                rounds: 1-4
      - constructorId: tyrrell
        engineManufacturerId: ford
        tyreManufacturerId: goodyear
        engineId: ford-dfy-v8-3-0
        drivers:
          - driverId: danny-sullivan
            rounds: 7-15
          - driverId: michele-alboreto
            rounds: 5-15
        chassis:
          - chassisId: tyrrell-011
            drivers:
              - driverId: danny-sullivan
                rounds: 7-13
              - driverId: michele-alboreto
                rounds: 5-10
          - chassisId: tyrrell-012
            drivers:
              - driverId: danny-sullivan
                rounds: 14-15
              - driverId: michele-alboreto
                rounds: 11-15
  ```

  Here two engines of the same engine manufacturer (Ford) were used (Ford DFV V8 3.0 and Ford DFY V8 3.0) by Benetton Tyrrell Team during 1983 season, so we have to constructor elements, allowing us to determine the precise combination of components (tyres/chassis/engine) used for each round and each driver in the entrant's season.

#### Structure:

Besides these additions, the structure remains the same, except that `tyreManufacturers` no longer appears for the concerned entrants (the tyre model data is now contained within the constructor elements).

#### Sources and information about some chassis:

To accomplish this work, my main source was [StatsF1](https://www.statsf1.com/en/default.aspx), which contains most of this data ([example here](https://www.statsf1.com/en/1950/france/engages.aspx)). When certain data was missing, I relied on Wikipedia by accessing the relevant race pages.

For a few races (notably the Indianapolis 500 in the early 1950s), some chassis don't have a full name beyond that of their constructor. By consulting the archives on the official site ([example here](https://www.indianapolismotorspeedway.com/events/indy500/history/historical-stats/race-stats/race-results/1950)) of this event, I observed that these chassis are simply named after their constructor. Therefore, for example, in 1950, there are chassis with only the name "Lesovsky" or "Nichels," as these have no additional information about their name on Wikipedia and the [Indianapolis Motor Speedway website](https://www.indianapolismotorspeedway.com/).

---

I hope this can be helpful. I remain available for any questions or improvements if needed.

Have a good day
[chassis-engines-entrants.zip](https://github.com/user-attachments/files/16626228/chassis-engines-entrants.zip)

**Comment by marceloverdijk** [comment]
Thx a lot!
I will have a look asap and will get back to you.

**Comment by marceloverdijk** [comment]
Thx again, it's a big piece of data ;-) I'm doing some verifications at the moment.

E.g. 1950:

```
- entrantId: automobiles-talbot-darracq
  countryId: france
  constructorId: talbot-lago
  engineManufacturerId: talbot-lago
  tyreManufacturerId: dunlop
  engineId: talbot-lago-23cv-l6-4-5
  drivers:
    - driverId: eugene-martin
      rounds: 1,4
    - driverId: louis-rosier
      rounds: 1,4-6
    - driverId: philippe-etancelin
      rounds: 1,5
    - driverId: raymond-sommer
      rounds: 6
    - driverId: yves-giraud-cabantous
      rounds: 1,4-6
  chassis:
    - chassisId: talbot-lago-t26c-da
      drivers:
        - driverId: eugene-martin
          rounds: 1,4
        - driverId: louis-rosier
          rounds: 4-6
        - driverId: philippe-etancelin
          rounds: 5
        - driverId: yves-giraud-cabantous
          rounds: 1,4-6
    - chassisId: talbot-lago-t26c
      drivers:
        - driverId: louis-rosier
          rounds: 1
        - driverId: philippe-etancelin
          rounds: 1
    - chassisId: talbot-lago-t26c-gs
      driverId: raymond-sommer
      rounds: 6
```

The data you provided above contains in a detailed level even which driver uses which chassis per rond.

Looking at e.g. wikipedia they have limited this data to just:

<img width="712" alt="image" src="https://github.com/user-attachments/assets/325a7332-9783-4add-96d4-a770a99cc072">

Which is more simplified, but limits the to which chassis were used per constructor per season. Thus not per race per driver.
In you use case do you need it per race/driver of would it be enough which chassis user for the constructors in a season?

In the latter case we could simplify the model quite a lot:

```
- entrantId: automobiles-talbot-darracq
  countryId: france
  constructorId: talbot-lago
  chassis:
    - chasisId: talbot-lago-t26c-da
    - chasisId: talbot-lago-t26c
    - chasisId: talbot-lago-t26c-gs
  engineManufacturerId: talbot-lago
  engines:
    - engineId: talbot-23cv-45-l6
  tyreManufacturerId: dunlop
  drivers:
    - driverId: eugene-martin
      rounds: 1,4
    - driverId: louis-rosier
      rounds: 1,4-6
    - driverId: philippe-etancelin
      rounds: 1,5
    - driverId: yves-giraud-cabantous
      rounds: 1,4-6
    - driverId: raymond-sommer
      rounds: 6
```

note the `chassis` and `engines` fields added above.

Would that be sufficient for your use case?
