### ISSUE TITLE
Engine and chassis are not specified per weekend.

### ISSUE THREAD

**Issue by Bjartur-I-Dali-Udbo** [f1db/f1db#48]
I am doing a qualifying summarisation and realised that chassis and engine entries are not defined in any of the files within each race weekend.
In cases of Ferrari using [F2002B ](https://en.wikipedia.org/wiki/Ferrari_F2002) and [F2004B](https://en.wikipedia.org/wiki/Ferrari_F2004) in the early stages of their following seasons, I can use alternate sources.
However, in 1992 Williams used two engines for the same chassis and here I have a harder time tracking down when the RS3 and RS4 engines were used.

```
- entrantId: canon-williams
  countryId: united-kingdom
  constructorId: williams
  engineManufacturerId: renault
  chassisId: williams-fw14b
  engines:
    - engineId: renault-rs3c-35-v10
    - engineId: renault-rs4-35-v10
  tyreManufacturerId: goodyear
  drivers:
    - driverId: nigel-mansell
      rounds: 1-16
    - driverId: riccardo-patrese
      rounds: 1-16
```
